name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.9.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0

    - name: Test workflow (local test data)
      run: mkdir -p $SNAKEMAKE_OUTPUT_CACHE
      env:
        SNAKEMAKE_OUTPUT_CACHE: snakemake-cache
      uses: snakemake/snakemake-github-action@v1.9.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs cache --conda-frontend mamba --cache get_genome get_annotation genome_faidx"

    - name: Test report
      uses: snakemake/snakemake-github-action@v1.9.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--report report.zip"
