name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.9.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0

    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v1.9.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--use-conda --cache --show-failed-logs -j 10 --conda-cleanup-pkgs cache --conda-frontend mamba"
        stagein: |
          export SNAKEMAKE_OUTPUT_CACHE=/snakemake-cache
          export TMPDIR=/tmp
          rm -rf .test/resources .test/results
          if [ -d $SNAKEMAKE_OUTPUT_CACHE ] ; then echo "cache-dir exists, clean and continue..." ; rm -rf $SNAKEMAKE_OUTPUT_CACHE && mkdir -p -m a+rw $SNAKEMAKE_OUTPUT_CACHE; else echo "cache-dir does not exist, creating..." ; mkdir -p -m a+rw $SNAKEMAKE_OUTPUT_CACHE;fi

    - name: Test report
      uses: snakemake/snakemake-github-action@v1.9.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--report report.zip"
